name:  Reporte de Bug
description: Reporta un problema o error en la aplicaci贸n
title: "[BUG] "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Gracias por tomarte el tiempo de reportar este bug. Por favor completa la informaci贸n a continuaci贸n.

  - type: textarea
    id: description
    attributes:
      label: Descripci贸n del bug
      description: Una descripci贸n clara y concisa del problema
      placeholder: Explica qu茅 sali贸 mal...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Pasos para reproducir
      description: Pasos para reproducir el comportamiento
      placeholder: |
        1. Ir a '...'
        2. Hacer clic en '...'
        3. Scroll hasta '...'
        4. Ver el error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportamiento esperado
      description: Describe qu茅 esperabas que sucediera
      placeholder: Deber铆a...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Comportamiento actual
      description: Describe qu茅 sucede actualmente
      placeholder: En su lugar...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Capturas de pantalla
      description: Si es aplicable, agrega capturas de pantalla
      placeholder: Arrastra y suelta im谩genes aqu铆

  - type: dropdown
    id: severity
    attributes:
      label: Severidad
      description: Qu茅 tan cr铆tico es este bug
      options:
        - Cr铆tico - Bloquea el uso de la aplicaci贸n
        - Alto - Funcionalidad importante no funciona
        - Medio - Problema notable pero hay workaround
        - Bajo - Problema menor o cosm茅tico
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Versi贸n
      description: 驴En qu茅 versi贸n encontraste el bug?
      placeholder: v1.0.0

  - type: dropdown
    id: environment
    attributes:
      label: Ambiente
      description: 驴D贸nde ocurre el problema?
      options:
        - Producci贸n
        - Desarrollo local
        - Docker
        - Otro
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs relevantes
      description: Copia y pega cualquier log relevante
      render: shell

  - type: textarea
    id: context
    attributes:
      label: Contexto adicional
      description: Agrega cualquier otro contexto sobre el problema
