name: ✨ Feature Request
description: Sugiere una nueva característica o mejora
title: "[FEATURE] "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ¡Gracias por sugerir una nueva característica! Tu feedback es muy valioso.

  - type: textarea
    id: problem
    attributes:
      label: ¿Qué problema resuelve esta característica?
      description: Describe el problema o necesidad que motiva esta solicitud
      placeholder: Me frustra que...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solución propuesta
      description: Describe cómo te gustaría que funcionara
      placeholder: Me gustaría poder...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas consideradas
      description: Describe soluciones alternativas que hayas considerado
      placeholder: También pensé en...

  - type: dropdown
    id: priority
    attributes:
      label: Prioridad
      description: ¿Qué tan importante es esta característica para ti?
      options:
        - Alta - Lo necesito para usar el sistema
        - Media - Mejoraría significativamente mi experiencia
        - Baja - Sería bueno tenerlo
    validations:
      required: true

  - type: dropdown
    id: user_type
    attributes:
      label: Tipo de usuario
      description: ¿Qué tipo de usuario se beneficiaría?
      options:
        - Usuario final
        - Administrador
        - Desarrollador
        - Todos
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups o ejemplos
      description: Si tienes mockups, wireframes o ejemplos, añádelos aquí

  - type: checkboxes
    id: willing_to_contribute
    attributes:
      label: Disposición para contribuir
      options:
        - label: Estoy dispuesto a trabajar en esta característica
        - label: Puedo ayudar con el diseño
        - label: Puedo ayudar con testing

  - type: textarea
    id: context
    attributes:
      label: Contexto adicional
      description: Agrega cualquier otro contexto o información relevante
